version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR:1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    restart: on-failure
    depends_on:
      - zookeeper

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    volumes:
      - ./test_producer.py:/test_producer.py
    container_name: producer
    # environment:
    #   - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    restart: on-failure
  
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    volumes:
      - ./test_consumer.py:/test_consumer.py
    container_name: consumer
    depends_on:
      - kafka
    restart: on-failure
